services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: premio-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - premio-net
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=premio_tjac
      - DB_USERNAME=premio
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - APP_URL=http://localhost:8080

  nginx:
    image: nginx:alpine
    container_name: premio-nginx
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - premio-net

  mysql:
    image: mysql:8.0
    container_name: premio-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: premio_tjac
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: premio
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - premio-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    container_name: premio-redis
    ports:
      - "6380:6379"
    networks:
      - premio-net

  mailpit:
    image: axllent/mailpit
    container_name: premio-mail
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - premio-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: premio-pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: premio
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    networks:
      - premio-net

networks:
  premio-net:
    driver: bridge

volumes:
  mysql-data:
